server {
  listen 8080;
  server_tokens off;
  root /usr/share/nginx/html;
  client_max_body_size 1m;
  add_header X-Content-Type-Options nosniff always;
  add_header X-Frame-Options DENY always;
  add_header Referrer-Policy no-referrer always;
  add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self'; frame-ancestors 'none'; object-src 'none'" always;
  location /api/ {
    proxy_pass http://audit-api:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 30s;
  }
  location / { try_files $uri $uri/ /index.html; }
}
