"""Initial frozen audit schema."""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_audit_log",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("actor", sa.String(length=254), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column(
            "detail",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_admin_audit_log_created_at"), "admin_audit_log", ["created_at"], unique=False)
    op.create_table(
        "admin_users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "durable_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_durable_jobs_available_at"), "durable_jobs", ["available_at"], unique=False)
    op.create_table(
        "enrollment_tokens",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "options",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column(
            "value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "vps",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("region", sa.String(length=128), nullable=True),
        sa.Column("provider", sa.String(length=128), nullable=True),
        sa.Column("hostname", sa.String(length=253), nullable=True),
        sa.Column("agent_version", sa.String(length=40), nullable=True),
        sa.Column("xray_version", sa.String(length=40), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "health",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agent_identities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("region", sa.String(length=128), nullable=True),
        sa.Column("independence_group", sa.String(length=128), nullable=True),
        sa.Column("mainland", sa.Boolean(), nullable=False),
        sa.Column("vps_id", sa.String(length=36), nullable=True),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["vps_id"],
            ["vps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_agent_identities_vps_id"), "agent_identities", ["vps_id"], unique=False)
    op.create_table(
        "audit_events_1m",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("vps_id", sa.String(length=36), nullable=False),
        sa.Column("bucket_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("bucket_seconds", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.BigInteger(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "source_ip", sa.String(length=45).with_variant(postgresql.INET(), "postgresql"), nullable=True
        ),
        sa.Column("destination_domain", sa.String(length=253), nullable=True),
        sa.Column(
            "destination_ip",
            sa.String(length=45).with_variant(postgresql.INET(), "postgresql"),
            nullable=True,
        ),
        sa.Column("destination_port", sa.Integer(), nullable=True),
        sa.Column("network", sa.String(length=3), nullable=False),
        sa.Column("inbound_tag", sa.String(length=128), nullable=True),
        sa.Column("outbound_tag", sa.String(length=128), nullable=True),
        sa.Column("decision", sa.String(length=8), nullable=False),
        sa.Column("connections", sa.BigInteger(), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["vps_id"],
            ["vps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_1m_bucket_start"), "audit_events_1m", ["bucket_start"], unique=False
    )
    op.create_index(
        "ix_event_destination_domain_time",
        "audit_events_1m",
        ["destination_domain", "bucket_start"],
        unique=False,
    )
    op.create_index(
        "ix_event_destination_ip_time", "audit_events_1m", ["destination_ip", "bucket_start"], unique=False
    )
    op.create_index("ix_event_node_id_time", "audit_events_1m", ["node_id", "bucket_start"], unique=False)
    op.create_index("ix_event_source_ip_time", "audit_events_1m", ["source_ip", "bucket_start"], unique=False)
    op.create_index("ix_event_user_id_time", "audit_events_1m", ["user_id", "bucket_start"], unique=False)
    op.create_index("ix_event_vps_id_time", "audit_events_1m", ["vps_id", "bucket_start"], unique=False)
    op.create_table(
        "audit_user_traffic",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("vps_id", sa.String(length=36), nullable=False),
        sa.Column("node_id", sa.BigInteger(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("interval_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("interval_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("uplink_bytes", sa.BigInteger(), nullable=False),
        sa.Column("downlink_bytes", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["vps_id"],
            ["vps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_user_traffic_interval_start"), "audit_user_traffic", ["interval_start"], unique=False
    )
    op.create_index("ix_traffic_user_time", "audit_user_traffic", ["user_id", "interval_start"], unique=False)
    op.create_index("ix_traffic_vps_time", "audit_user_traffic", ["vps_id", "interval_start"], unique=False)
    op.create_table(
        "login_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("admin_id", sa.String(length=36), nullable=False),
        sa.Column("csrf_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["admin_users.id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index(op.f("ix_login_sessions_expires_at"), "login_sessions", ["expires_at"], unique=False)
    op.create_table(
        "probe_targets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("vps_id", sa.String(length=36), nullable=False),
        sa.Column(
            "address", sa.String(length=45).with_variant(postgresql.INET(), "postgresql"), nullable=False
        ),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("protocol", sa.String(length=8), nullable=False),
        sa.Column("server_name", sa.String(length=253), nullable=True),
        sa.Column("path", sa.String(length=256), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["vps_id"],
            ["vps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vps_id", "address", "port", "protocol"),
    )
    op.create_index(op.f("ix_probe_targets_vps_id"), "probe_targets", ["vps_id"], unique=False)
    op.create_table(
        "vps_ip_history",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("vps_id", sa.String(length=36), nullable=False),
        sa.Column(
            "address", sa.String(length=45).with_variant(postgresql.INET(), "postgresql"), nullable=False
        ),
        sa.Column("family", sa.Integer(), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["vps_id"],
            ["vps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vps_ip_history_address"), "vps_ip_history", ["address"], unique=False)
    op.create_index(op.f("ix_vps_ip_history_vps_id"), "vps_ip_history", ["vps_id"], unique=False)
    op.create_table(
        "block_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("vps_id", sa.String(length=36), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=True),
        sa.Column(
            "target_ip", sa.String(length=45).with_variant(postgresql.INET(), "postgresql"), nullable=False
        ),
        sa.Column("target_port", sa.Integer(), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_known_good_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_known_bad_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recovered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("probe_count", sa.Integer(), nullable=False),
        sa.Column(
            "evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["probe_targets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vps_id"],
            ["vps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_block_events_detected_at"), "block_events", ["detected_at"], unique=False)
    op.create_index(op.f("ix_block_events_vps_id"), "block_events", ["vps_id"], unique=False)
    op.create_table(
        "probe_results",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("probe_id", sa.String(length=36), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("control_ok", sa.Boolean(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("error_class", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["probe_id"],
            ["agent_identities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["probe_targets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("probe_id", "target_id", "started_at"),
    )
    op.create_index(op.f("ix_probe_results_started_at"), "probe_results", ["started_at"], unique=False)
    op.create_index("ix_probe_target_time", "probe_results", ["target_id", "started_at"], unique=False)
    op.create_table(
        "received_batches",
        sa.Column("agent_id", sa.String(length=36), nullable=False),
        sa.Column("batch_id", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.String(length=12), nullable=False),
        sa.Column("body_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agent_identities.id"],
        ),
        sa.PrimaryKeyConstraint("agent_id", "batch_id"),
    )
    op.create_index(op.f("ix_received_batches_created_at"), "received_batches", ["created_at"], unique=False)
    op.create_table(
        "block_event_correlations",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("block_event_id", sa.String(length=36), nullable=False),
        sa.Column("entity_type", sa.String(length=20), nullable=False),
        sa.Column("entity_key", sa.String(length=253), nullable=False),
        sa.Column("connections", sa.BigInteger(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["block_event_id"], ["block_events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("block_event_id", "entity_type", "entity_key"),
    )
    op.create_index(
        op.f("ix_block_event_correlations_block_event_id"),
        "block_event_correlations",
        ["block_event_id"],
        unique=False,
    )
    op.create_index(
        "ix_correlation_entity", "block_event_correlations", ["entity_type", "entity_key"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_correlation_entity", table_name="block_event_correlations")
    op.drop_index(op.f("ix_block_event_correlations_block_event_id"), table_name="block_event_correlations")
    op.drop_table("block_event_correlations")
    op.drop_index(op.f("ix_received_batches_created_at"), table_name="received_batches")
    op.drop_table("received_batches")
    op.drop_index("ix_probe_target_time", table_name="probe_results")
    op.drop_index(op.f("ix_probe_results_started_at"), table_name="probe_results")
    op.drop_table("probe_results")
    op.drop_index(op.f("ix_block_events_vps_id"), table_name="block_events")
    op.drop_index(op.f("ix_block_events_detected_at"), table_name="block_events")
    op.drop_table("block_events")
    op.drop_index(op.f("ix_vps_ip_history_vps_id"), table_name="vps_ip_history")
    op.drop_index(op.f("ix_vps_ip_history_address"), table_name="vps_ip_history")
    op.drop_table("vps_ip_history")
    op.drop_index(op.f("ix_probe_targets_vps_id"), table_name="probe_targets")
    op.drop_table("probe_targets")
    op.drop_index(op.f("ix_login_sessions_expires_at"), table_name="login_sessions")
    op.drop_table("login_sessions")
    op.drop_index("ix_traffic_vps_time", table_name="audit_user_traffic")
    op.drop_index("ix_traffic_user_time", table_name="audit_user_traffic")
    op.drop_index(op.f("ix_audit_user_traffic_interval_start"), table_name="audit_user_traffic")
    op.drop_table("audit_user_traffic")
    op.drop_index("ix_event_vps_id_time", table_name="audit_events_1m")
    op.drop_index("ix_event_user_id_time", table_name="audit_events_1m")
    op.drop_index("ix_event_source_ip_time", table_name="audit_events_1m")
    op.drop_index("ix_event_node_id_time", table_name="audit_events_1m")
    op.drop_index("ix_event_destination_ip_time", table_name="audit_events_1m")
    op.drop_index("ix_event_destination_domain_time", table_name="audit_events_1m")
    op.drop_index(op.f("ix_audit_events_1m_bucket_start"), table_name="audit_events_1m")
    op.drop_table("audit_events_1m")
    op.drop_index(op.f("ix_agent_identities_vps_id"), table_name="agent_identities")
    op.drop_table("agent_identities")
    op.drop_table("vps")
    op.drop_table("settings")
    op.drop_table("enrollment_tokens")
    op.drop_index(op.f("ix_durable_jobs_available_at"), table_name="durable_jobs")
    op.drop_table("durable_jobs")
    op.drop_table("admin_users")
    op.drop_index(op.f("ix_admin_audit_log_created_at"), table_name="admin_audit_log")
    op.drop_table("admin_audit_log")
    # ### end Alembic commands ###
