<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import InfoPanel from './InfoPanel.vue'
import BarChart from './BarChart.vue'
import {timezone,formatDate} from './dates'
type Row = Record<string, unknown>
const email = ref(''), password = ref(''), csrf = ref(sessionStorage.getItem('audit_csrf') || document.cookie.split('; ').find(x=>x.startsWith('audit_csrf='))?.split('=')[1] || '')
const role = ref(''), error = ref(''), busy = ref(false), current = ref('overview')
const data = ref<Row[]>([]), detail = ref<Row | null>(null), summary = ref<Row>({}), system = ref<Row>({})
const page = ref(1), more = ref(false), query = ref(''), entity = ref('domains'), incident = ref('')
const start = ref(new Date(Date.now()-86400000).toISOString().slice(0,16)), end = ref(new Date().toISOString().slice(0,16))
const settingsText = ref(''), enrollment = ref(''), tokenKind = ref('agents'), mainland = ref(false), group = ref('')
const vpsId = ref(''), targetIp = ref(''), targetPort = ref(443), targetProtocol = ref('tcp'), targetSni = ref('')
const manualNotes = ref(''), lookback = ref(60), newEmail = ref(''), newPassword = ref(''), newRole = ref('viewer')
const nav = [ ['overview','总览'], ['vps','VPS 管理'], ['events','审计搜索'], ['block-events','被墙事件'], ['correlation','关联度'], ['probe-targets','探测目标'], ['probe-results','探测记录'], ['identities','Agent / Probe'], ['traffic','用户流量'], ['admin-users','后台账户'], ['admin-audit-log','操作记录'], ['settings','系统设置'], ['system','系统状态'] ]
const filterVps=ref(''), filterNode=ref(''), filterUser=ref(''), filterRegion=ref(''), filterProvider=ref(''), filterState=ref('')
const editName=ref(''), editRegion=ref(''), editProvider=ref(''), editGroup=ref(''), editMainland=ref(false), editEnabled=ref(true), editRole=ref('viewer'), editPassword=ref('')
const currentPassword=ref(''), changedPassword=ref('')
const names: Record<string,string> = {reachability:'大陆可达状态',status:'在线状态',current_ip:'当前 IP',offline_vps:'离线 VPS',events_24h:'24h 聚合记录',recovered_24h:'24h 已恢复',email:'邮箱',role:'权限',address:'目标 IP',independence_group:'独立网络组',mainland:'大陆探测点',bucket_start:'时间',vps_id:'VPS',node_id:'节点 ID',user_id:'XBoard 用户',source_ip:'来源 IP',destination_domain:'目标域名',destination_ip:'目标 IP',destination_port:'端口',connections:'连接次数',name:'名称',region:'区域',provider:'供应商',state:'状态',score:'关联度',entity_key:'对象',block_event_id:'事件',last_heartbeat_at:'最后心跳',target_ip:'探测 IP',target_port:'端口',detected_at:'检测时间',started_at:'探测时间',success:'成功',control_ok:'控制目标正常',error_class:'错误分类',latency_ms:'延迟 ms',agent_version:'Agent 版本',kind:'类型',enabled:'启用',uplink_bytes:'上行字节',downlink_bytes:'下行字节',interval_start:'区间开始',interval_end:'区间结束',total_vps:'VPS 总数',online_vps:'在线 VPS',connections_24h:'24h 连接数',users_24h:'24h 用户数'}
const fieldEntities: Record<string,string> = {user_id:'users',source_ip:'source-ips',destination_domain:'domains',destination_ip:'destination-ips'}
const stateNames: Record<string,string> = {normal:'正常',unknown:'证据不足',online:'在线',offline:'离线',suspected:'疑似屏蔽',confirmed:'确认屏蔽',recovered:'已恢复',false_positive:'误报',manual:'手动事件'}
const columns = computed(() => Object.keys(data.value[0] || {}).filter(k => !['id','health','evidence','details','created_at','token_hash'].includes(k)).slice(0,12))
function display(value: unknown): string { if(value == null) return '—'; if(typeof value === 'object') return JSON.stringify(value); const s=String(value); if(/^\d{4}-\d{2}-\d{2}T/.test(s)) return formatDate(s); return stateNames[s] || s }
async function api(path: string, method='GET', body?: unknown) {
  const response = await fetch('/api/v1/'+path, {method, credentials:'same-origin', headers:{'Content-Type':'application/json','X-CSRF-Token':csrf.value}, body:body === undefined ? undefined : JSON.stringify(body)})
  const value = await response.json()
  if(!response.ok) { if(response.status===401) role.value=''; throw new Error(value.detail || `请求失败 ${response.status}`) }
  return value
}
async function run(action: () => Promise<void>) { busy.value=true;error.value='';try{await action()}catch(e){error.value=String(e)}finally{busy.value=false} }
function clearSession(){sessionStorage.removeItem('audit_csrf')}
async function login(){await run(async()=>{ const result=await api('auth/login','POST',{email:email.value,password:password.value});csrf.value=result.csrf_token;sessionStorage.setItem('audit_csrf',csrf.value);role.value=result.role;password.value='';await load() })}
function range(){return `start=${encodeURIComponent(start.value+':00Z')}&end=${encodeURIComponent(end.value+':00Z')}`}
async function load(){
 timezone.value=(await api('settings')).timezone
 detail.value=null
 if(current.value==='overview'){summary.value=await api('events/summary');return}
 if(current.value==='system'){system.value=await api('system/health');return}
 if(current.value==='settings'){settingsText.value=JSON.stringify(await api('settings'),null,2);return}
 let path=current.value
 let params=`page_number=${page.value}&size=50`
 if(['events','probe-results','traffic'].includes(path)) params+='&'+range()
 if(path==='events' && query.value) {path='search';params+='&q='+encodeURIComponent(query.value)}
 if(['events','traffic','block-events','probe-targets'].includes(path)&&filterVps.value)params+='&vps_id='+encodeURIComponent(filterVps.value)
 if(['events','traffic'].includes(path)&&filterUser.value)params+='&user_id='+encodeURIComponent(filterUser.value)
 if(path==='events'&&filterNode.value)params+='&node_id='+encodeURIComponent(filterNode.value)
 if(path==='vps'){if(filterRegion.value)params+='&region='+encodeURIComponent(filterRegion.value);if(filterProvider.value)params+='&provider='+encodeURIComponent(filterProvider.value)}
 if(path==='block-events'&&filterState.value)params+='&state='+encodeURIComponent(filterState.value)
 if(path==='correlation') {path+='/' + entity.value;if(incident.value)params+='&event_id='+encodeURIComponent(incident.value);if(query.value)params+='&key='+encodeURIComponent(query.value)}
 const result=await api(path+'?'+params);data.value=result.items;more.value=result.has_more
}
async function navigate(key:string){current.value=key;page.value=1;await run(load)}
async function open(row:Row){await run(async()=>{if(current.value==='vps')detail.value=await api('vps/'+row.id);else if(current.value==='block-events')detail.value=await api('block-events/'+row.id);else detail.value=row;editName.value=String(row.name||'');editRegion.value=String(row.region||'');editProvider.value=String(row.provider||'');editGroup.value=String(row.independence_group||'');editMainland.value=Boolean(row.mainland);editEnabled.value=Boolean(row.enabled);editRole.value=String(row.role||'viewer');editPassword.value=''})}
async function inspectEntity(field:string,key:unknown){await run(async()=>{detail.value=await api('entities/'+fieldEntities[field]+'/'+encodeURIComponent(String(key))+'?'+range())})}
async function windowSearch(){start.value=String(detail.value?.window_start||'').slice(0,16);end.value=String(detail.value?.window_end||'').slice(0,16);filterVps.value=String(detail.value?.vps_id||'');query.value='';await navigate('events')}
async function createToken(){await run(async()=>{const result=await api('enrollment-tokens','POST',{kind:tokenKind.value,mainland:mainland.value,independence_group:group.value,vps_id:tokenKind.value==='agents'&&vpsId.value?vpsId.value:null});enrollment.value=result.token})}
async function saveSettings(){await run(async()=>{await api('settings','PATCH',JSON.parse(settingsText.value));await load()})}
async function addTarget(){await run(async()=>{await api('probe-targets','POST',{vps_id:vpsId.value,address:targetIp.value,port:targetPort.value,protocol:targetProtocol.value,server_name:targetSni.value||null});await load()})}
async function manual(){await run(async()=>{await api('block-events','POST',{vps_id:vpsId.value,target_ip:targetIp.value,target_port:targetPort.value,first_known_bad_at:end.value+':00Z',lookback_minutes:lookback.value,notes:manualNotes.value});await load()})}
async function correlationsFor(){incident.value=String(detail.value?.id||'');query.value='';await navigate('correlation')}
async function exportCsv(){await run(async()=>{const response=await fetch('/api/v1/export?'+range(),{credentials:'same-origin'});if(!response.ok)throw new Error('导出失败，请缩小时间范围');const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download='audit.csv';a.click();URL.revokeObjectURL(url)})}
async function saveDetail(){await run(async()=>{let body:Row={};if(current.value==='vps')body={name:editName.value,region:editRegion.value,provider:editProvider.value};if(current.value==='identities')body={name:editName.value,region:editRegion.value,independence_group:editGroup.value,mainland:editMainland.value,enabled:editEnabled.value};if(current.value==='admin-users')body={role:editRole.value,enabled:editEnabled.value,...(editPassword.value?{password:editPassword.value}:{})};await api(current.value+'/'+detail.value?.id,'PATCH',body);await load()})}
onMounted(async()=>{try{const result=await api('auth/me');role.value=result.role;await run(load)}catch{role.value=''}})
</script>

<template>
 <div v-if="!role" class="login"><form @submit.prevent="login"><p class="eyebrow">XBOARD · OPERATIONS</p><h1>审计与关联分析</h1><p>多 VPS 运行状况与事件调查</p><label>管理员邮箱<input v-model="email" type="email" autocomplete="username" required></label><label>密码<input v-model="password" type="password" autocomplete="current-password" required></label><button :disabled="busy">登录</button><p role="alert" class="error">{{error}}</p></form></div>
 <div v-else class="layout">
  <aside><h2>XBoard Audit</h2><p class="muted">运行观测 / 关联调查</p><nav><button v-for="[key,label] in nav" :key="key" :class="{active:current===key}" @click="navigate(key)" :disabled="role!=='admin'&&['identities','admin-users','admin-audit-log'].includes(key)">{{label}}</button></nav><small>{{role==='admin'?'管理员':'只读访问'}}</small><button @click="run(async()=>{await api('auth/logout','POST');role='';clearSession()})">退出登录</button></aside>
  <main><header><div><p class="eyebrow">MULTI-VPS AUDIT PLATFORM</p><h1>{{nav.find(x=>x[0]===current)?.[1]}}</h1></div><button :disabled="busy" @click="run(load)">{{busy?'加载中…':'刷新'}}</button></header>
   <p class="notice">关联度反映事件前后的统计关联，不代表已证明的屏蔽原因。来源 IP 不等同于个人身份。</p>
   <p v-if="error" role="alert" class="error">{{error}}</p>
   <section v-if="current==='overview'"><div class="cards"><article v-for="key in ['total_vps','online_vps','offline_vps','recovered_24h','events_24h','connections_24h','users_24h']" :key="key"><span>{{names[key]}}</span><strong>{{display(summary[key])}}</strong></article></div><h2>事件状态</h2><div class="cards"><article v-for="(value,key) in (summary.states as Row)" :key="key"><span>{{stateNames[key]||key}}</span><strong>{{value}}</strong></article></div><div class="charts"><BarChart title="近 30 天事件" :items="(summary.charts as any)?.incidents"/><BarChart title="最近 24h 连接 / VPS" :items="(summary.charts as any)?.vps"/><BarChart title="事件窗口域名关联度" :items="(summary.charts as any)?.domain"/><BarChart title="用户关联度" :items="(summary.charts as any)?.user"/><BarChart title="来源 IP 关联度" :items="(summary.charts as any)?.source_ip"/></div></section>
   <section v-else-if="current==='system'"><dl><template v-for="(value,key) in system" :key="key"><dt>{{key}}</dt><dd>{{display(value)}}</dd></template></dl></section>
   <section v-else-if="current==='settings'"><details><summary>修改我的密码</summary><form @submit.prevent="run(async()=>{await api('auth/password','POST',{current_password:currentPassword,new_password:changedPassword});currentPassword='';changedPassword='';role='';clearSession()})"><input v-model="currentPassword" type="password" autocomplete="current-password" placeholder="当前密码" required><input v-model="changedPassword" type="password" autocomplete="new-password" placeholder="新密码（至少 14 字符）" minlength="14" required><button>保存并重新登录</button></form></details><p>保留期、探测共识、调查窗口、评分权重和忽略域名。权重之和须为 1。</p><textarea v-model="settingsText" rows="24" :readonly="role!=='admin'" aria-label="系统设置 JSON"></textarea><button v-if="role==='admin'" @click="saveSettings">保存设置</button><details v-if="role==='admin'"><summary>新增后台账户</summary><form @submit.prevent="run(async()=>{await api('admin-users','POST',{email:newEmail,password:newPassword,role:newRole});newPassword='';newEmail=''})"><input v-model="newEmail" type="email" placeholder="邮箱" required><input v-model="newPassword" type="password" minlength="14" placeholder="密码（至少 14 字符）" required><select v-model="newRole"><option value="viewer">只读</option><option value="admin">管理员</option></select><button>创建账户</button></form></details></section>
   <section v-else>
    <div v-if="['events','traffic','block-events','probe-targets','vps'].includes(current)" class="toolbar"><input v-if="current!=='vps'" v-model="filterVps" placeholder="按 VPS ID 筛选"><template v-if="['events','traffic'].includes(current)"><input v-model="filterUser" placeholder="用户 ID"><input v-if="current==='events'" v-model="filterNode" placeholder="节点 ID"></template><template v-if="current==='vps'"><input v-model="filterRegion" placeholder="区域"><input v-model="filterProvider" placeholder="供应商"></template><select v-if="current==='block-events'" v-model="filterState"><option value="">全部状态</option><option v-for="state in ['suspected','confirmed','recovered','false_positive','manual']" :value="state">{{stateNames[state]}}</option></select><button @click="page=1;run(load)">筛选</button></div>
    <div class="toolbar" v-if="['events','traffic','probe-results','correlation'].includes(current)"><label>开始（UTC）<input v-model="start" type="datetime-local"></label><label>结束（UTC）<input v-model="end" type="datetime-local"></label><input v-if="current==='events'||current==='correlation'" v-model="query" placeholder="用户 / IP / 域名 / VPS / 节点"><select v-if="current==='correlation'" v-model="entity"><option value="domains">目标域名</option><option value="users">用户</option><option value="source-ips">来源 IP</option><option value="destination-ips">目标 IP</option></select><button @click="page=1;run(load)">查询</button><button v-if="current==='events'&&role==='admin'" @click="exportCsv">导出 CSV</button></div>
    <p v-if="current==='traffic'" class="muted">此处为用户 / 节点总流量，不是目标域名流量。</p>
    <details v-if="current==='identities'&&role==='admin'"><summary>创建一次性注册令牌</summary><div class="toolbar"><select v-model="tokenKind"><option value="agents">VPS Agent</option><option value="probes">Probe</option></select><input v-if="tokenKind==='agents'" v-model="vpsId" placeholder="轮换已有 VPS 凭据时填写 VPS ID"><label><input type="checkbox" v-model="mainland">大陆探测点</label><input v-model="group" placeholder="独立网络分组（同网络使用相同组）"><button @click="createToken">生成 15 分钟令牌</button></div><p v-if="enrollment" class="token">{{enrollment}}</p><p>在下载的项目目录运行 install-audit-agent.sh 或 probe/install-probe.sh，按提示输入此令牌。</p></details>
    <details v-if="['vps','probe-targets'].includes(current)&&role==='admin'"><summary>添加探测目标</summary><form class="toolbar" @submit.prevent="addTarget"><input v-model="vpsId" placeholder="VPS ID" required><input v-model="targetIp" placeholder="公网 IP" required><input v-model.number="targetPort" type="number" min="1" max="65535"><select v-model="targetProtocol"><option>tcp</option><option>tls</option><option>http</option><option>https</option></select><input v-model="targetSni" placeholder="TLS SNI / HTTP Host"><button>保存目标</button></form></details>
    <details v-if="current==='block-events'&&role==='admin'"><summary>创建手动事件</summary><form class="toolbar" @submit.prevent="manual"><input v-model="vpsId" placeholder="VPS ID" required><input v-model="targetIp" placeholder="IP" required><input v-model.number="targetPort" type="number"><label>首次异常（UTC）<input v-model="end" type="datetime-local"></label><select v-model.number="lookback"><option v-for="m in [15,30,60,180,360,1440]" :value="m">{{m}} 分钟</option></select><input v-model="manualNotes" placeholder="备注"><button>创建</button></form></details>
    <div class="table-wrap"><table><thead><tr><th v-for="col in columns" :key="col">{{names[col]||col}}</th><th>详情</th></tr></thead><tbody><tr v-for="(row,index) in data" :key="String(row.id||index)"><td v-for="col in columns" :key="col"><button v-if="fieldEntities[col]&&row[col]!=null" class="link" @click="inspectEntity(col,row[col])">{{display(row[col])}}</button><span v-else>{{display(row[col])}}</span></td><td><button @click="open(row)">查看</button><button v-if="current==='identities'&&role==='admin'&&row.enabled" @click="run(async()=>{await api('identities/'+row.id,'DELETE');await load()})">撤销</button><button v-if="current==='probe-targets'&&role==='admin'" @click="run(async()=>{await api('probe-targets/'+row.id,'PATCH',{enabled:!row.enabled});await load()})">{{row.enabled?'停用':'启用'}}</button></td></tr></tbody></table><p v-if="!data.length" class="empty">当前筛选下暂无数据</p></div>
    <footer><button :disabled="page===1||busy" @click="page--;run(load)">上一页</button><span>第 {{page}} 页 · 每页 50 条</span><button :disabled="!more||busy" @click="page++;run(load)">下一页</button></footer>
    <section v-if="detail" class="detail"><button @click="detail=null">关闭详情</button><h2>调查详情</h2><div v-if="current==='block-events'" class="toolbar"><button @click="correlationsFor">查看事件关联度</button><button @click="windowSearch">搜索调查时间窗</button><button v-if="role==='admin'" @click="run(async()=>{await api('block-events/'+detail?.id+'/recalculate','POST')})">重新计算</button></div><form v-if="['vps','identities','admin-users'].includes(current)&&role==='admin'&&detail.id" class="toolbar" @submit.prevent="saveDetail"><template v-if="current!=='admin-users'"><input v-model="editName" placeholder="名称" required><input v-model="editRegion" placeholder="区域"></template><input v-if="current==='vps'" v-model="editProvider" placeholder="供应商"><template v-if="current==='identities'"><input v-model="editGroup" placeholder="独立网络组"><label><input v-model="editMainland" type="checkbox">大陆探测点</label></template><template v-if="current==='admin-users'"><select v-model="editRole"><option value="viewer">只读</option><option value="admin">管理员</option></select><input v-model="editPassword" type="password" minlength="14" placeholder="重置密码（留空保留）"></template><label v-if="current!=='vps'"><input v-model="editEnabled" type="checkbox">启用</label><button>保存</button></form><BarChart v-if="detail.connection_trend" title="连接趋势" :items="detail.connection_trend as any"/><BarChart v-if="(detail.activity_24h as any)?.connection_trend" title="最近 24h 连接趋势" :items="(detail.activity_24h as any).connection_trend"/><InfoPanel :value="detail"/></section>
   </section>
  </main>
 </div>
</template>
